### ISSUE TITLE
The progress bar for the offline result upload is having issues on the survey listing screen.

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#1]
1. The progress bar is not visible on the survey listing page.
2. The "Completed" status is getting displayed only when the user refresh or move from another screen to the survey listing screen.

**Comment by dinesh-opg** [comment]
This issue is fixed

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
