### ISSUE TITLE
Loading of questions inside an offline survey for the tablet version of the app is bit odd and slow.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#10]
Loading of questions inside an offline survey for the tablet version of the app is bit odd and slow.

**Comment by veereshms** [comment]
The issue is still present.

**Comment by veereshms** [comment]
Issue is fixed and verified.

**Comment by dinesh-opg** [comment]
The issue is we are using an async task in the cordova plugin for performing of task in background instead of main thread.
Removed the background asynctask and performing it in main thread only.
