### ISSUE TITLE
Getting 404 error for password reset link received in forgot password email

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#12]
Getting 404 error for password reset link received in forgot password email

http://adminsuite.staging.onepointglobal.com/appwebsite/ResetPassword?data=aqwBmBGkXmrn/M+Wf7YR9/tY/+ZX+SZFkdJBT7/UWbo+9gyVxB3Ib1+6Pd4ci36ueRDQog8hqJVSOQeBYUk1zhFIxCwFWMqgd7tAqlMDPyHV8pJg3xWvakrUeuccW9JsryeG/BEZYqwtdleWl8nPxvC4QvO+QxPBX3FVeslgsm5B8OCqDtgT4u7M9ALXF28LG21E+79xQZair22xLfLKbVm5nQ0GTxufKkJQCplgWUTG1YYgzWgatB9xJooaAVAOWtEcyQ3/oF6UMgsfZuVScDT3b359QvwwMSQ3MH0+BtUYxaBSWOjboP6ZvhwIbNYL2DXEEWMTjfYCDmWiAelo88Vd5/QDo1cWY3ZZLHyrp80=

![image](https://user-images.githubusercontent.com/26476914/30096831-37076baa-92f8-11e7-9a9d-4f2a16bbc9cb.png)

**Comment by dinesh-opg** [comment]
Actually the url is changed from http://adminsuite.staging.onepointglobal.com/ to http://adminsuitestaging.onepointglobal.com/ So in the mail it should be replaced with the new url
