### ISSUE TITLE
In forgot your password screen it is showing "Please enter a valid e-mail ID." error message even though entered email id is valid.

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#14]
In forgot your password screen it is showing "Please enter a valid e-mail ID." error message even though entered email id is valid.

![screenshot_20170918-171741](https://user-images.githubusercontent.com/26476914/30541208-fc6e5cf2-9c97-11e7-92c3-8359dc1f1ca2.png)

**Comment by dinesh-opg** [comment]
This issue is releated to the backend.

**Comment by vivek-onepoint** [comment]
This issue is because of not having shared key in the Header (Only in SDK header will contain SharedKey).
Changes are been made to handle both the scenarios (Mysurveys App or SDK). Will be available to staging in release.

**Comment by vivek-onepoint** [comment]
Hi,
As per asked by @Chinthan for the response to be changed if the email passed does not exist and other changes in response as per the parameter is been passed are done and updated in Dev server. It will move to staging in release and QC can also have look to it.

I have tested the response using postman and its working fine after the changes been made. You can confirm once its updated.

**Comment by onepointpb** [comment]
Now it is working in the app and SDK both.
