### ISSUE TITLE
If an existing theme is replaced with new logo and background then it is not reflecting.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#15]
If an existing theme is replaced with new logo and background then it is not reflecting.

**Comment by dinesh-opg** [comment]
The issue we are not downloading the media everytime when we call the  sdk method downloadmedia .We are internally checking whether the file is present in the app folders .If the image is present in app folder we don't download.
Now where ever we call the downloadmedia method in the sdk we will  download the new file to replace the existing file.
Now the theme change is reflecting as expected.

**Comment by onepointpb** [comment]
This is working in the latest app (v2.0.1) provided.
