### ISSUE TITLE
Changing country code is crashing the signed live app.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#16]
Changing country code is crashing the signed live app.

**Comment by dinesh-opg** [comment]
The above issue is related to the proguard .It is encrypted by proguard.So we have added a progaurd rule for not encrypting that particular class searchview class.

**Comment by onepointpb** [comment]
Now clicking on country code is not crashing the app. Verified the fix.
