### ISSUE TITLE
App notifications are not working

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#2]
App notifications are not working. May be it is from the back-end.

**Comment by dinesh-opg** [comment]
The notifications are working fine in dev.Please check the above with backend team.

**Comment by veereshms** [comment]
Notifications are working now, but has below issues.
1) Junk values are coming in notification when we use macros in message and also text we have written in message is not coming. 

Actual message:
![image](https://user-images.githubusercontent.com/26476914/30162285-df806832-93f1-11e7-9bb1-589594dff0f4.png)

Message received in notification:
![image](https://user-images.githubusercontent.com/26476914/30163783-e219d960-93f7-11e7-8643-971ae55b8494.png)


2) Notifications keeping coming even after we terminate notification in admin suite by clicking Quit.

**Comment by dinesh-opg** [comment]
There is an issue in sending the notification from adminsuite to app.Actually we are getting the same key username and password instead of the actual values

**Comment by abhi-onepoint** [comment]
All good with API & Notification service. But there is a issue with data saved I.e macros notation are replaced with %20 html tags (They should have open and closed curly braces **'{ }'**). And some macro name should be changed in order to get values in notification.
_Do check email notification body for reference_

**Comment by deepika-Gopala** [comment]
Special characters are unescaped now and conversion is removed so the symbols will appear as is with {}.

**Comment by onepointpb** [comment]
App notifications are not working.

**Comment by NeerajOPG** [comment]
@onepointpb  We are able to send the notification from Firebase Console.
@abhi-onepoint can you check this issue.

**Comment by abhi-onepoint** [comment]
Push notifications are working in both IOS and Android platform - Issue with certificate and set up, which is fixed.

**Comment by onepointpb** [comment]
App notifications are working.
