### ISSUE TITLE
VideoPreview is not working 

### ISSUE THREAD

**Issue by dinesh-opg** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#22]
VideoPreview is not working.While taking the media question in the survey.I have noticed this issue in the android 7.0 and above.

**Comment by NeerajOPG** [comment]
Video Preview is not working because we have not added this "FLAG_GRANT_READ_URI_PERMISSION" flag in intent. We need to add extra flag "Intent.FLAG_GRANT_READ_URI_PERMISSION" in intent to start activity to open video in Android nougat and Oreo.

**Comment by onepointpb** [comment]
Verified in a device having Oreo.
