### ISSUE TITLE
Unable to fetch the result for the demo offline survey (Phoenix). 

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#23]
Scenario
1. Take the offline survey.
2. On the last question click Submit. Then wait for 5 second for the url in the script to open.
2. As the device is offline, it will not redirect to the url and show error.
3. Return to the survey description screen. It shows status as "Pending". But still it allows the user to upload the result.
4. On checking the cache file and export nothing is present that refer to this survey.

**Comment by NeerajOPG** [comment]
The results are uploading for Offline Survey and also we can export the result from account tool kit. Only problem is survey status is not updating properly both for online and offline survey in MySurveysApp.

**Comment by NeerajOPG** [comment]
The script which we are testing is not suitable for mobile apps so this is not an issue with MySurveys app.
