### ISSUE TITLE
If the size of profile image is more, then loading the image under Profile section of the app is taking very long time.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#24]
As a result logging out of the app is also getting interrupted.

**Comment by dinesh-opg** [comment]
The issue is the profile image size is more when downloading and we are downloading the png image format .So it is taking more time to download.
Now the profile image is compressed if its size is more than 2 M.B and downloading a jpeg image instead of png.

**Comment by onepointpb** [comment]
verified
