### ISSUE TITLE
Issues in the attached offline script.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#25]
Attached the script below. In the script:

1. While entering any input the keyboard is covering covers the input area. So the entered input is not visible. 
2. the range validation is working for "text_q1" question. But the error message contains extra texts. For e.g. "Question '{QUESTION}' ({QUESTION_NUMBER}): The answer does not have enough text, current length is 4, minimum is 5." It has to be corrected.
3. "define_q1" and "define_q2" are getting skipped.
4. for "num_Loop_q1" the range validation is working. But the error message contains extra texts. For e.g.  "Question '{QUESTION}' ({QUESTION_NUMBER}): The answer does not have enough text, current length is 4, minimum is 5." It has to be corrected.

Points 1 and 2 are known issues for all offline surveys. 
Click [here](https://github.com/OnePointGlobal/OnePoint-Global-MySurveys-App-iOS/files/1361678/061017.zip) to download the script.

**Comment by NeerajOPG** [comment]
I have fixed point number 3 & 5 . I am working on other points.

**Comment by NeerajOPG** [comment]
I have fixed point number 4.

**Comment by onepointpb** [comment]
The above points are fixed and tested.
