### ISSUE TITLE
Loading of questions in an offline survey is very slow.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#26]
Loading of questions in an offline survey is very slow.

**Comment by NeerajOPG** [comment]
The loading of offline survey is now better. Previously while generating the html file we are writing the each html tag parallely to target.html file means performing many file write operation. Now we are storing the generated html in local  StringBuffer variable and writing it  to file in one operation.

**Comment by onepointpb** [comment]
The loading has improved now.
