### ISSUE TITLE
In masking questions the entered numbers are not displayed in correct order.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#27]
The email masking is working. But rest of the masking present in the attached script are showing issues in both online and offline survey.
Click [here](https://github.com/OnePointGlobal/OnePoint-Global-MySurveys-App-iOS/files/1361678/061017.zip) to download the script.

**Comment by NeerajOPG** [comment]
This is fixed. 
We have to change the control type of Question from **singlelineedit** to **numbermasking** in the  OneScript.
Click [here ](https://github.com/OnePointGlobal/OnePoint-Global-MySurveys-App-Android/files/1688379/Masking.zip) to download modified script.

**Comment by onepointpb** [comment]
1. In Samsung Galaxy S7, the entered numbers are not in correct order. 
2. In Nexus smartphones, the keyboard is having a right arrow button (as in screenshot below) which generally means "Done". After entering the numbers if the user clicks on the button, the input box is getting refreshed and the default values are getting displayed instead of the entered numbers.
![image](https://user-images.githubusercontent.com/26476815/35722500-92872288-081c-11e8-96eb-f155518dbb8a.png)

**Comment by NeerajOPG** [comment]
I have fixed 2. I have modified Player.js to handle the keypress event for input = "tel".
