### ISSUE TITLE
UniqueId doesn't exist

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#3]
Getting uniqueId doesn't exist in the mysurveys app.while making any api call 
in mysurveys app.

**Comment by veereshms** [comment]
Issue is fixed.

**Comment by dinesh-opg** [comment]
The uniqueID doesn't exist happens when the unique id is expired in the backend.
We are handling the  uniqueID doesn't exist in the opgsdk.
