### ISSUE TITLE
In the latest app (MySurveys2.0_Version_2.0.2_LIVE_SIGNED.apk) the fixes for few issues are not updated.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#30]
1. While running the Phoenix offline survey backward the options in multiple choice questions disappeared. This is not the case in the runtime build (MySurveys_2.0.runtime.apk) provided before.
2. Fix for points 2 and 4 in #25 also not updated in this build.

**Comment by NeerajOPG** [comment]
In this script we  have different two  LayoutTemplate("pheonixmarketing.htm" & "pheonixmarketing2.htm") for different questions so it was not picking the correct LayoutTemplate file for questions when you go backward.

**Comment by onepointpb** [comment]
Verified
