### ISSUE TITLE
Matrix questions are not displayed properly inside offline survey.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#31]
This issue is in tablet and iPad both. Even with default survey theme it is not displayed correctly.

![image](https://user-images.githubusercontent.com/26476815/32780150-47296962-c966-11e7-87d8-12acca4aefb4.png)

**Comment by NeerajOPG** [comment]
This issue has been fixed.The html was not generating properly for this question and some there was some css issues.

**Comment by onepointpb** [comment]
Verified.
