### ISSUE TITLE
If the content of QR code is more then it is not getting displayed properly.

### ISSUE THREAD

**Issue by NeerajOPG** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#35]
If the content of QR code is more then it is not getting displayed properly.
for example if data in qr code is "https://account.onepointglobal.com/#/surveys/location/0" 
but it is not displayed full.
![barcoderesult](https://user-images.githubusercontent.com/26483692/33753829-73417114-dc0f-11e7-9551-4c908fe0a446.png)

**Comment by NeerajOPG** [comment]
This issue is fixed.
 We have added {'padding': '10px 0','word-wrap' : 'break-word'} in style.
We will include it in next release.
![barcoderesult2](https://user-images.githubusercontent.com/26483692/33762744-ad4033c2-dc33-11e7-9273-7f1a0bf8aa6f.png)

**Comment by onepointpb** [comment]
Verified in staging app.
