### ISSUE TITLE
Performance of latest My Surveys app is slow when there are many co-ordinates attached to a particular address.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#36]
Performance of latest My Surveys app is slow when there are many co-ordinates attached to a particular address.

**Comment by NeerajOPG** [comment]
The performance of the has increased now we are plotting the surveys which are visible to the user.
Still working on it to make it more faster.

**Comment by NeerajOPG** [comment]
The issue is fixed in 2.0.3.
