### ISSUE TITLE
Live app is crashing on the Profile screen.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#37]
**Device specification/configuration:**
Device Model: Samsung Galaxy Fame S6810
Android OS Version - 4.1.2
RAM - 512 MB

**Comment by NeerajOPG** [comment]
The issue is fixed in 2.0.4.

**Comment by onepointpb** [comment]
Now it is not crashing on profile screen.
