### ISSUE TITLE
Enhancement: There are few enhancements in different modules. Please check the description.

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#4]
1. While entering email id in Forgot Password screen there is no gap between the text and the line. Keep it like the change password screen.
2. When there is success in Change Password screen make all the fields blank.
3. Make the font of the text bit dark in the detailed notification screen.

**Comment by veereshms** [comment]
Points 1 and 3 are fixed.
But for point 2, the fields are getting blank. But it would be better if it 
displays like a fresh screen instead of the cursor blinking on the old password 
field.

**Comment by dinesh-opg** [comment]
All the above enhancements  are fixed .

**Comment by veereshms** [comment]
@ Point 2: The cursor is still blinking on confirm password field.

**Comment by dinesh-opg** [comment]
This issue is fixed 
There was nothing wrong .
Just an enhancement we need to clear the focus for the last edit text after clearing all the edit texts after password change is successfully

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
