### ISSUE TITLE
Not able to update the profile picture in Samsung Galaxy Fame S6810

### ISSUE THREAD

**Issue by NeerajOPG** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#41]
Not able to update the profile picture in Samsung Galaxy Fame S6810
Device specification/configuration:
Device Model: Samsung Galaxy Fame S6810
Android OS Version - 4.1.2
RAM - 512 MB
![device-2017-12-20-121928](https://user-images.githubusercontent.com/26483692/34195002-67935654-e581-11e7-8b77-e7aa5989c9e1.png)

**Comment by onepointpb** [comment]
Now able to update profile picture in Samsung Galaxy Fame S6810.
