### ISSUE TITLE
Signature question is not working in Samsung Galaxy Fame S6810.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#46]
Device specification/configuration:
Device Model: Samsung Galaxy Fame S6810
Android OS Version - 4.1.2
RAM - 512 MB
MySurveys Vesion - 2.0.4

**Comment by NeerajOPG** [comment]
The issue is fixed in 2.0.4.

**Comment by onepointpb** [comment]
It is working now.
