### ISSUE TITLE
App is crashing after logout when we login with Google.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#48]
This is the case with the following build:
"MySurveys2.0_Version_2.0.4_LIVE_SIGNED.apk".

**Comment by dinesh-opg** [comment]
The issue is related to status message we are getting null status message from google signout callback.We have added one condition to check the status message is null or not.

**Comment by dinesh-opg** [comment]
The issue is related to status message we are getting null status message from google signout callback.We have added one condition to check the status message is null or not.

**Comment by onepointpb** [comment]
Now the app is not crashing after logout.
