### ISSUE TITLE
Back button is disabled in Survey

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#5]
Not able to go back to the app in the middle of an survey. Back button is disabled. Only after completing the survey the back button is enabled. This is happening in both offline and online survey.

**Comment by veereshms** [comment]
The back button is now enabled .You can come back when you are in middle of an 
survey.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.

**Comment by dinesh-opg** [comment]
The back button is disabled in the cordova webview in the codova library.Now it is being enable in the cordova library.
