### ISSUE TITLE
Request permission dialog keep on displaying in By Location Survey

### ISSUE THREAD

**Issue by NeerajOPG** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#51]
Steps to reproduce issue  [link](https://drive.google.com/file/d/1-_ATwJ6OouAZE52C6ixdIq-9vWIpalCb/view)

**Comment by NeerajOPG** [comment]
We have fixed this issue in "MySurveys2.0_Version_2.0.5".

**Comment by onepointpb** [comment]
Verified
