### ISSUE TITLE
Capture image by camera is not working if camera permission is denied and not showing dialog

### ISSUE THREAD

**Issue by NeerajOPG** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#52]
please check video to reproduce the issue. [video](https://drive.google.com/file/d/1qNtg3_09un1TPV_3CboGMVJN9WIbSC1f/view)

**Comment by NeerajOPG** [comment]
We have fixed this issue in "MySurveys2.0_Version_2.0.5".
Added the respective permission check and showing the permission dialog.

**Comment by onepointpb** [comment]
Verified the fix.
