### ISSUE TITLE
MySurveys App asking for permission after closing the app

### ISSUE THREAD

**Issue by NeerajOPG** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#53]
![permission_dialog_error](https://user-images.githubusercontent.com/26483692/36366651-1513e438-1575-11e8-8a37-e74ee7521312.png)

**Comment by NeerajOPG** [comment]
We have fixed this issue in "MySurveys2.0_Version_2.0.5".

**Comment by onepointpb** [comment]
Verified.
