### ISSUE TITLE
In the latest app for testing (MySurveys2.0_Version_2.0.5_STAGING.apk), the custom controls are not getting invoked on the first click.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#54]
On second click the custom controls are working fine. 
This issue is only in the online survey. This issue was not there in the previous builds.

**Comment by dinesh-opg** [comment]
We are getting the issue as 'TypeError: cordova.exec is not a function'

**Comment by NeerajOPG** [comment]
We have fixed this issue in "MySurveys2.0_Version_2.0.5".
First time Cordova web-view is taking time to respond to click events after that it will work fine.

**Comment by onepointpb** [comment]
Working now.
