### ISSUE TITLE
Issue in downloading the panel logo and the panel background images

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#58]
It is taking too much time for downloading the panel related images. It just displays loading for a long time.

**Comment by dinesh-opg** [comment]
There is issue when we refresh the app .The panel images are not downloaded.Now we have made code changes to fix this issue.Now this is working fine you can test it.

**Comment by hitesh-opg** [comment]
This is now working!
