### ISSUE TITLE
Screen goes blank for some time while uploading media files

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#6]
Scenario 1: Try to upload a media file for media upload question in a survey, once we choose file from gallery or capture through camera it is taking more time to select and also screen goes blank for few seconds.

Scenario 2: Try to upload profile picture by capturing new image through camera or choose from gallery, same issue happens as mentioned in scenario 1.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.

**Comment by dinesh-opg** [comment]
The process of uploading media is happening in the main thread so it blocking the ui.So we need to handle this in a asynctask.
