### ISSUE TITLE
In the survey details screen the schedule information is showing a dummy date range instead of "unscheduled", if the survey is not having any schedule information.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#64]
This is working fine for English language. But for rest of the translations it is showing the above mentioned issue.

**Comment by dinesh-opg** [comment]
Issue is fixed.
The comparison of the date string is happen with the default english string instead of the translated date string.Now we are comparing the using the translated date string.It is working fine now.

**Comment by onepointpb** [comment]
Working fine in the latest build shared.
