### ISSUE TITLE
Geolocation question showing problem with google maps

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#65]
Geolocation question showing problem with google maps. Screenshot will be shared separately.

**Comment by Manjunath-Ramesh** [comment]
Looks like Google API key needs to be added/ updated from the UI side. Needs to be discussed with the team.

**Comment by pavithra-opg** [comment]
Hi Guys,
- When we try to use the web link and choose the location, it displays the below error message. Same is the case when we try the geo-location question in preview mode:
![image1](https://user-images.githubusercontent.com/28919270/43640929-6e8fe0b0-973f-11e8-9faf-3799b90c19c6.png)

- When we run a project using Studio, it throws the below message and also it says development purpose only:
![image2](https://user-images.githubusercontent.com/28919270/43640977-9150b5b6-973f-11e8-9404-03d2da3db771.png)

**Comment by nikul-opg** [comment]
For this issue, we have removed the google map and now we are using the mapquest.

**Comment by pavithra-opg** [comment]
Issue reported is fixed.
