### ISSUE TITLE
In-app notifications are displayed with in the app notification tab

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#68]
All the notifications scheduled as in-app are residing within the app's notification tab and there is no pop-up to the user.

**Comment by dinesh-opg** [comment]
The issue is related to android version compactability with the new android version 8.0 and above.For the android versions above 8.0 should have a notification channel for displaying the notification on the notification bar.So we created the notification channel so the issue is fixed.
