### ISSUE TITLE
The camera interface is opening in reverse mode for the tablet version of the app while using Barcode scan inside a survey.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#8]
The camera interface is opening in reverse mode while using Barcode scan inside a survey. Changing the device to portrait or landscape does not affect this as well.
But the default Camera app and other Scanner apps are opening the interface correctly.

**Comment by dinesh-opg** [comment]
This issue is fixed.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
