### ISSUE TITLE
Uploading a small video is showing error for online survey in the tablet version of the app.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#9]
1. The message says: "Video Upload failed : An error occured. Please try again, else contact support."
2. A 3 second video got uploaded but a 7 second video did not.
3. In the error message there is a typo. "occured" should be "occurred". If it is from back-end then it has to be corrected there.

**Comment by dinesh-opg** [comment]
This issue is fixed

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
